### ISSUE TITLE
TODO: patch generation.

### ISSUE THREAD

**Issue by darkrsw** [kupl/erc-group2-framework#2]
- [ ] `def run(src_dir, test_dir)` <= `project_root`도 받아야 하지 않을까?
- [ ] 현재는 Line 단위 생성만 지원. Function, block 단위의 생성도 지원해야 할 것.
- [ ] 어떤 logger를 사용할지?
- [ ] pipeline을 한 패치당 하나씩 validation할지, shotgun 방식으로 여러개의 patch를 만들어서 batch로 validation할지 결정.
